# EFQRCode Jazzy config
module: EFQRCode

author: EyreFree

theme: fullwidth
readme: README.md
documentation: USERGUIDE.md
output: ./docs
swift_version: 5.0
exclude:
  - ./*

include:
  - ./Source/*.swift
# xcodebuild_arguments: [SWIFT_VRSION=4.2]